name: Libretro Android Build

on:
  workflow_dispatch:

jobs:
  build-libretro-stage1:
    name: LR stage 1
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.short-sha.outputs.sha }}
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - name: Expose Actions environment
        uses: white-axe/expose-actions-environment@v1

      - name: Checkout repository
        uses: taiki-e/checkout-action@v1

      - id: short-sha
        name: Get Git commit hash
        run: |
          sha=$(git rev-parse --short=7 HEAD)
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl build-essential automake libtool zip universal-ctags ruby nodejs npm
          npm install @actions/artifact@4 fast-glob@3

      - name: Set up WASI SDK
        run: |
          curl -Lo ${{ runner.temp }}/wasi-sdk.tar.gz https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-30/wasi-sdk-30.0-x86_64-linux.tar.gz
          mkdir ${{ runner.temp }}/wasi-sdk
          tar -xzf ${{ runner.temp }}/wasi-sdk.tar.gz -C ${{ runner.temp }}/wasi-sdk --strip-components=1
          rm ${{ runner.temp }}/wasi-sdk.tar.gz

      - name: Set up Binaryen
        run: |
          curl -Lo ${{ runner.temp }}/binaryen.tar.gz https://github.com/WebAssembly/binaryen/releases/download/version_126/binaryen-version_126-x86_64-linux.tar.gz
          mkdir ${{ runner.temp }}/binaryen
          tar -xzf ${{ runner.temp }}/binaryen.tar.gz -C ${{ runner.temp }}/binaryen --strip-components=1
          rm ${{ runner.temp }}/binaryen.tar.gz

      - name: Build stage 1
        run: |
          cd libretro
          CLICOLOR_FORCE=1 make -j $(nproc) WASI_SDK=${{ runner.temp }}/wasi-sdk WASM_OPT=${{ runner.temp }}/binaryen/bin/wasm-opt

      - id: upload-artifact
        name: Upload artifact
        run: |
          node --input-type=module -e '
            import {DefaultArtifactClient} from "@actions/artifact";
            import fg from "fast-glob";
            import fs from "fs";
            process.chdir("libretro/build/libretro-stage1");
            const artifact = new DefaultArtifactClient();
            const {id, size} = await artifact.uploadArtifact(
              "stage1.${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}-${{ steps.short-sha.outputs.sha }}",
              fg.globSync("**"),
              ".",
            );
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `artifact-id=${id}`);
          '

  build-libretro-android:
    needs: build-libretro-stage1
    name: LR Android ${{ matrix.arch_mkxpz }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch_mkxpz: armv7
            arch_llvm: armv7a-linux-androideabi21
            arch_cmake: armv7-a
            cpu_family: arm
            cpu: generic-armv7-a
            endian: little
          - arch_mkxpz: arm64
            arch_llvm: aarch64-linux-android21
            arch_cmake: aarch64
            cpu_family: aarch64
            cpu: generic-armv8-a
            endian: little
          - arch_mkxpz: x86
            arch_llvm: i686-linux-android21
            arch_cmake: i686
            cpu_family: x86
            cpu: i686
            endian: little
          - arch_mkxpz: x86_64
            arch_llvm: x86_64-linux-android21
            arch_cmake: x86_64
            cpu_family: x86_64
            cpu: x86_64
            endian: little
    steps:
      - name: Expose Actions environment
        uses: white-axe/expose-actions-environment@v1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential llvm meson cmake nodejs npm
          npm install @actions/artifact@4 fast-glob@3

      - id: ndk
        name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          add-to-path: false

      - name: Checkout repository
        uses: taiki-e/checkout-action@v1

      - name: Download stage 1
        run: |
          node --input-type=module -e '
            import {DefaultArtifactClient} from "@actions/artifact";
            const artifact = new DefaultArtifactClient();
            await artifact.downloadArtifact(${{ needs.build-libretro-stage1.outputs.artifact-id }}, {
              path: "libretro/build/libretro-stage1",
            });
          '

      - name: Configure core
        run: |
          echo "[binaries]" | tee -a ${{ runner.temp }}/cross.ini
          echo "c = ['${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang', '--target=${{ matrix.arch_llvm }}']" | tee -a ${{ runner.temp }}/cross.ini
          echo "cpp = ['${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++', '--target=${{ matrix.arch_llvm }}']" | tee -a ${{ runner.temp }}/cross.ini
          echo "ar = '${{ steps.ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'" | tee -a ${{ runner.temp }}/cross.ini
          echo "cmake = 'cmake'" | tee -a ${{ runner.temp }}/cross.ini
          echo "[host_machine]" | tee -a ${{ runner.temp }}/cross.ini
          echo "system = 'android'" | tee -a ${{ runner.temp }}/cross.ini
          echo "cpu_family = '${{ matrix.cpu_family }}'" | tee -a ${{ runner.temp }}/cross.ini
          echo "cpu = '${{ matrix.cpu }}'" | tee -a ${{ runner.temp }}/cross.ini
          echo "endian = '${{ matrix.endian }}'" | tee -a ${{ runner.temp }}/cross.ini
          echo "[cmake]" | tee -a ${{ runner.temp }}/cross.ini
          echo "CMAKE_SYSTEM_PROCESSOR = '${{ matrix.arch_cmake }}'" | tee -a ${{ runner.temp }}/cross.ini
          echo '--------------------------------------------------------------------------------'
          CLICOLOR_FORCE=1 meson setup build --cross-file ${{ runner.temp }}/cross.ini --buildtype release -Db_lto=true -Dlibretro=true -Dlibretro_save_states=true

      - name: Build core
        run: |
          mkdir ${{ runner.temp }}/dist
          cd build
          CLICOLOR_FORCE=1 ninja -v
          llvm-strip mkxp-z_libretro.so
          mv mkxp-z_libretro.so ${{ runner.temp }}/dist/mkxp-z_libretro_android.so

      - name: Upload artifact
        run: |
          node --input-type=module -e '
            import {DefaultArtifactClient} from "@actions/artifact";
            import fg from "fast-glob";
            process.chdir("${{ runner.temp }}/dist");
            const artifact = new DefaultArtifactClient();
            await artifact.uploadArtifact(
              "mkxp-z_libretro.android.${{ matrix.arch_mkxpz }}.${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}-${{ needs.build-libretro-stage1.outputs.sha }}",
              fg.globSync("**"),
              ".",
            );
          '

